spring:
  application:
    name: test

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  datasource:
      url: jdbc:mysql://localhost:3306/testDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ssafy
      password: ssafy